import { cpSync, existsSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { Plugin } from 'vite'


function getAllFiles(dir: string, fileList: string[] = []): string[] {
    const files = readdirSync(dir)

    for (const file of files) {
        const filePath = resolve(dir, file)
        if (statSync(filePath).isDirectory()) {
            getAllFiles(filePath, fileList)
        } else {
            fileList.push(filePath)
        }
    }

    return fileList
}

export function AssetSyncPlugin(rootDir: string, resourcesDir: string, modName: string): Plugin {
    return {
        name: 'vuetale-asset-sync',
        apply: 'build',
        enforce: 'pre',
        buildStart() {
            const assetsDir = resolve(rootDir, 'lib', 'assets')
            this.addWatchFile(assetsDir) // Watch the entire assets directory for changes
            const targetDir = resolve(resourcesDir, 'Common/UI/Custom', modName)

            if (!existsSync(assetsDir)) return

            const filesAbsolute = getAllFiles(assetsDir)
            const files = filesAbsolute.map(file => file.replace(assetsDir, '').substring(1))

            // Generate TS autocompletion file
            const tsFile = resolve(rootDir, 'lib', 'assets.ts')

            let tsSrc = `// Autogenerated file\n\n`

            if (files.length > 0) {
                tsSrc += `export type AssetFile = ${files.map(path => `"${path}"`).join(' | ')}\n`
            } else {
                tsSrc += `export type AssetFile = never\n // No assets found`
            }
            tsSrc += `export function $asset(path: AssetFile): string { return '../@${modName}/' + path }\n`
            // Write the asset file
            writeFileSync(tsFile, tsSrc)

            if (files.length === 0) return

            filesAbsolute.forEach(file => this.addWatchFile(file))



            // Keep destination clean so deleted assets are removed too.
            rmSync(targetDir, { recursive: true, force: true })
            cpSync(assetsDir, targetDir, { recursive: true })
        },
    }
}