import { createHash } from 'node:crypto'
import { resolve } from 'node:path'
import fs from 'node:fs'
import type { Plugin, ResolvedConfig } from 'vite'

/**
 * Vite plugin that injects Vue HMR plumbing into .vue SFCs at build time.
 *
 * Only active when `vite build --mode development` (i.e. the watch script).
 * Production builds are unaffected.
 *
 * How it works:
 *   @vitejs/plugin-vue compiles each SFC's `<script setup>` into a virtual
 *   module with the id pattern `*.vue?vue&type=script&setup=true&...`.
 *   That module ends with:
 *       export default /* @__PURE__ *\/ _defineComponent({ __name: "Foo", ... });
 *
 *   This plugin intercepts that virtual module (enforce: 'post'), converts the
 *   inline default export to a named const, appends __hmrId, and registers the
 *   component with Vue's __VUE_HMR_RUNTIME__:
 *       const __vtHmrComp = /* @__PURE__ *\/ _defineComponent({ ... });
 *       __vtHmrComp.__hmrId = "<hash>";
 *       if (typeof __VUE_HMR_RUNTIME__ !== 'undefined') {
 *           const __vtIsNew = __VUE_HMR_RUNTIME__.createRecord(__vtHmrComp.__hmrId, __vtHmrComp);
 *           if (!__vtIsNew) __VUE_HMR_RUNTIME__.reload(__vtHmrComp.__hmrId, __vtHmrComp);
 *       }
 *       export default __vtHmrComp;
 *
 *   createRecord returns false when the component is already registered → the
 *   second evaluation (by JSEngine.reloadModule) automatically calls reload,
 *   updating all live component instances without an engine restart.
 *
 * Additionally copies vue.global.js (Vue dev IIFE) to the output as vue.dev.js
 * so JSEngine loads it automatically and __VUE_HMR_RUNTIME__ is available in V8.
 */
export function HmrIdsPlugin(): Plugin {
    let cfg: ResolvedConfig | undefined

    return {
        name: 'vuetale-hmr-ids',
        enforce: 'post',

        apply(_, { command, mode }) {
            return command === 'build' && mode === 'development'
        },

        configResolved(resolvedConfig) {
            cfg = resolvedConfig
        },

        transform(code, id) {
            // Only handle the virtual script sub-modules generated by @vitejs/plugin-vue.
            // These have the form: *.vue?vue&type=script&setup=true&lang.ts
            if (!id.includes('?vue&type=script')) return null

            // The source .vue file path sits before the '?' query string.
            const sourceId = id.split('?')[0]
            const hmrId = createHash('sha256').update(sourceId).digest('hex').slice(0, 8)

            // Match:  export default /* @__PURE__ */ _defineComponent(
            //    or:  export default _defineComponent(
            // and convert the inline expression to a named const so we can attach __hmrId.
            const modified = code.replace(
                /export default (\/\* @__PURE__ \*\/ )?(_defineComponent\()/,
                'const __vtHmrComp = $1$2'
            )

            // If the pattern wasn't found the SFC uses a different shape – bail out.
            if (modified === code) return null

            const injection = [
                '',
                '// [Vuetale HMR] injected by HmrIdsPlugin',
                `__vtHmrComp.__hmrId = "${hmrId}";`,
                'if (typeof __VUE_HMR_RUNTIME__ !== \'undefined\') {',
                '    const __vtIsNew = __VUE_HMR_RUNTIME__.createRecord(__vtHmrComp.__hmrId, __vtHmrComp);',
                '    if (!__vtIsNew) __VUE_HMR_RUNTIME__.reload(__vtHmrComp.__hmrId, __vtHmrComp);',
                '}',
                'export default __vtHmrComp;',
                '',
            ].join('\n')

            return { code: modified + injection, map: null }
        },

        closeBundle() {
            if (!cfg) return
            // vue.dev.js must land at the resources root (src/main/resources/vue.dev.js),
            // NOT inside the Vite outDir (vuetale/core/) which is wiped by emptyOutDir.
            // loadSourceText("vue.dev.js") resolves relative to devResourcesPath which
            // is the resources root, so this path is correct.
            const outDir = resolve(cfg.root, cfg.build.outDir)
            // outDir = .../src/main/resources/vuetale/core  →  go up two levels
            const resourcesRoot = resolve(outDir, '../..')

            const vueDev = resolve(cfg.root, 'node_modules/vue/dist/vue.global.js')
            if (fs.existsSync(vueDev)) {
                const dest = resolve(resourcesRoot, 'vue.dev.js')
                fs.copyFileSync(vueDev, dest)
                console.log(`[Vuetale HMR] Copied vue.global.js → ${dest}`)
            } else {
                console.warn('[Vuetale HMR] vue.global.js not found – partial HMR will be unavailable')
            }
        },
    }
}

